### ISSUE TITLE
40d9f0efcae1ab61302cc3b90a75385c31966578 broke linter-js-standard

### ISSUE THREAD

**Issue by despairblue** [AtomLinter/atom-linter#20]
https://github.com/AtomLinter/atom-linter/commit/40d9f0efcae1ab61302cc3b90a75385c31966578 broke linter-js-standard. See https://github.com/ricardofbarros/linter-js-standard/issues/30

**Comment by despairblue** [comment]
It's late, so if I'm wrong I'm sorry, but I think that's what lead to it.

**Comment by steelbrain** [comment]
We've had that problem with `linter-jshint` too, it's on windows, and is related to providing `process.env` to the child processes

**Comment by steelbrain** [comment]
Fixed by #22

**Comment by despairblue** [comment]
Could you elaborate more? I can't see how this is related :confused: 

So #22 allows for linters that write things to stderr and and the lint errors to stdout? Also I'm on linux, and the bug seems to only affect windows.

**Comment by despairblue** [comment]
I just tested the new version. #22 does not fix what I outlined [in this comment](https://github.com/ricardofbarros/linter-js-standard/issues/30#issuecomment-123925052).

I'm afraid https://github.com/AtomLinter/atom-linter/commit/40d9f0efcae1ab61302cc3b90a75385c31966578 should have been a major version update since it changed existing behavior.

Before that it was possible to have a linter that outputs text (`standard: Use JavaScript Standard Style (https://github.com/feross/standard`) to stderr and the errors to stdout. Now it's not possible anymore. Linters that output anything on stderr but their errors (these are on stdout) can't reach [this line](https://github.com/AtomLinter/atom-linter/blob/master/lib/helpers.coffee#L30)

It's weird behavior from `standard` to do so, but it is what it is :disappointed:

**Comment by despairblue** [comment]
Ah, [here](https://github.com/feross/standard/issues/112) was the decission made that the errors go to stdout and everything else to stderr, it acutally makes sense with this interpretation of stdout and stderr:

> The general semantics of stdout is "content I'm interested in if I'm running this program" and stderr is "any content that is not related to the functionality of this program"

**Comment by rogy** [comment]
Also having this problem

**Comment by steelbrain** [comment]
@despairblue We are only able to fix the problems that we can reproduce, if you would provide us a minimal reproduction case, that would be great.

**Comment by steelbrain** [comment]
Ah right, by re-reading your messages a few time, I think you want stuff from stdout and don't want it to throw errors when it gets something in stderr, right?

**Comment by despairblue** [comment]
Yeah. Sorry, was I that unclear :anguished:

**Comment by steelbrain** [comment]
will solve it right away, sorry it took so long

**Comment by steelbrain** [comment]
@despairblue what would you suggest the name of the option to be?

**Comment by despairblue** [comment]
`throwOnStdErr`? Which would defaults to `false`, to reestablish the old behavior.

**Comment by AsaAyers** [comment]
I don't think it should default to false even if that matches the old behavior.

When you run a command and expect to get output on `stdout`, then something on `stderr` should indicate something is wrong. That's why the code was added to throw when something unexpected shows up there. If you default `throwOnStdErr` to false, then it requires linters to *opt-in* to protecting them against unexpected errors. It should default to `true` and the few linters that read `stdin` but for some reason expect `stderr` to output junk should opt-out of that protection.

**Comment by despairblue** [comment]
Defaulting to `true` is definitely what it should be in the end. And the change itself was a good idea as well, it just should have been a major version bump.

For the sake of semantic versioning I'm for defaulting to `false`, release 2.0.5, then let it default to true and release 3.0.0 (that was actually @steelbrain idea and I think it's good one).

That would unbreak linters that didn't expect this change while making the sane behaviour available to all linters that are updated frequently.

**Comment by AsaAyers** [comment]
I think that sounds like a reasonable compromise :+1:

**Comment by steelbrain** [comment]
I am so glad we all agree :tada:

**Comment by steelbrain** [comment]
A fix is up in https://github.com/AtomLinter/atom-linter/pull/24 defaulting it to false as discused, will be default to true after a version bump
